// <auto-generated />
using System;
using Invoice_web_2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace invoiceweb2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Invoice_web_2.Models.Invoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Num");

                    b.Property<double>("SubTotal");

                    b.Property<double>("Total");

                    b.Property<int>("cantidad");

                    b.Property<string>("cliente");

                    b.Property<DateTime>("fecha");

                    b.Property<int>("producto");

                    b.HasKey("ID");

                    b.ToTable("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
